# Boilerplate Rails RESTful JSON API

This API is implemented according to the [JSON API spec v1.1](https://jsonapi.org/format/1.1/)

## Filtering
**Description:** JSON API filtering with `all_filters` as default matcher.

**URI example:** `GET /users?filter[email-eq]=user@email.com&filter[name-cont]=son&match=any_filters`

## Sorting
**Description:** JSON API sorting.

**URI example:** `GET /users?sort=name,-age`

## Inclusion
**Description:** JSON API inclusion of related resources. Dot-separated relationship path supporting not implemented at this time.

**URI example:** `GET /users?include=team,organization`

## Pagination
**Description:** JSON API pagination with offset strategy.

**URI example:** `GET /users?page[number]=1&page[size]=1`

# Group Session


## Sessions [/users/session]


### Create user session (Sign In) [POST /api/v1/users/session]


+ Request renders user whose session was created
**POST**&nbsp;&nbsp;`/api/v1/users/session`

    + Headers

            Accept: application/json
            Content-Type: application/json

    + Body

            {
              "email": "franklin@hodkiewiczjenkins.us",
              "password": "rHdA0I1rBBD"
            }

+ Response 201

    + Headers

            Content-Type: application/vnd.api+json; charset=utf-8

    + Body

            {
              "data": {
                "id": "868",
                "type": "account",
                "attributes": {
                  "email": "franklin@hodkiewiczjenkins.us",
                  "created_at": "2019-08-17T13:56:23.498Z"
                }
              },
              "meta": {
                "csrf": "ucDAtTtz5fhasNhjUTlnxda9VTqZRWU7HxBGenXATr5uRO6roL94J14aUYMvqe63r2Qhyn6VTb1gpHrWheeL5A==",
                "access": "eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NjYwNTM3ODMsImFjY291bnRfaWQiOjg2OCwidWlkIjoiMzFlNTAwYjctZDk3Yi00ZTgxLTk1ZTEtNWE5ZWFhNTdmYWE1IiwiZXhwIjoxNTY2MDUzNzgzfQ.__dVyZe3eIWW3AUWJfdr4j51CG6E21l9WaRF-qDZUr8",
                "access_expires_at": "2019-08-17T17:56:23.000+03:00",
                "refresh": "eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NjYwNTM3ODMsInVpZCI6ImY0YTFjZDZjLTJhYmUtNGRhYi04MDRkLTYzNjFkNGUzNmZiNyIsImV4cCI6MTU2NjY1NDk4M30.kd_RckWgBfFJAbfHt5VsgzSmXlmECdptfRpZ0MGI9TQ",
                "refresh_expires_at": "2019-08-24T16:56:23.000+03:00"
              }
            }

+ Request renders resource errors
**POST**&nbsp;&nbsp;`/api/v1/users/session`

    + Headers

            Accept: application/json
            Content-Type: application/json

    + Body



+ Response 422

    + Headers

            Content-Type: application/vnd.api+json; charset=utf-8

    + Body

            {
              "errors": [
                {
                  "source": {
                    "pointer": "/email"
                  },
                  "detail": "is missing"
                },
                {
                  "source": {
                    "pointer": "/password"
                  },
                  "detail": "is missing"
                }
              ]
            }

+ Request returns not found status
**POST**&nbsp;&nbsp;`/api/v1/users/session`

    + Headers

            Accept: application/json
            Content-Type: application/json

    + Body

            {
              "email": "_sally@green.ca",
              "password": "zg2ejjMgdvS"
            }

+ Response 404

    + Headers

            Content-Type: application/json

+ Request renders auth errors
**POST**&nbsp;&nbsp;`/api/v1/users/session`

    + Headers

            Accept: application/json
            Content-Type: application/json

    + Body

            {
              "email": "yanira@johnston.info",
              "password": "_c51ghoD6B"
            }

+ Response 401

    + Headers

            Content-Type: application/vnd.api+json; charset=utf-8

    + Body

            {
              "errors": [
                {
                  "source": {
                    "pointer": "/base"
                  },
                  "detail": "wrong credentials"
                }
              ]
            }

### Destroy user session (Sign Out) [DELETE /api/v1/users/session]


+ Request clears user session
**DELETE**&nbsp;&nbsp;`/api/v1/users/session`

    + Headers

            Accept: application/json
            X-Refresh-Token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NjYwNTM3ODMsInVpZCI6ImYyNjYwMjZlLTIzMzEtNDg2MS1iM2M4LWI3ZmE4YTZiNTJiMyIsImV4cCI6MTU2NjY1NDk4M30.0Owv7mVryS3LEkwRb3uuTc0PY3H6wVGIlNiJSzPtWd8
            Content-Type: application/json

+ Response 204

+ Request renders auth errors
**DELETE**&nbsp;&nbsp;`/api/v1/users/session`

    + Headers

            Accept: application/json
            X-Refresh-Token: wrong_token
            Content-Type: application/json

+ Response 401

    + Headers

            Content-Type: application/vnd.api+json; charset=utf-8

    + Body

            {
              "errors": [
                {
                  "source": {
                    "pointer": "/base"
                  },
                  "detail": "invalid_token"
                }
              ]
            }
