aws: Do not use for Test and Development
  access_key_id:
  secret_access_key:
  s3:
    region: A region where we have stored a bucket
    bucket: S3 bucket name

redis:
  db: The name of container in staging and production (redis://service_name:6379).
      redis://localhost:6379 for test and development.

smtp:
  address: Domain address of email service
  user_name: An email
  password: A password from email box

db:
  host: Domain of RDS instance
  port: 5432
  database: Database name from RDS
  user: User name for access to DB on RDS
  password: Password to RDS DB
  pool: 5

sentry_dsn: Not used. Used for notify in a SLACK channel.
