version: 2

updates:
  - package-ecosystem: "bundler"
    directory: "/"
    # Check for new versions every Sunday (or every month)
    schedule:
      interval: "weekly" # `interval: "monthly"`
      day: "sunday"
    labels:
      - "dependency"
      - "need review"
    # Disable automatic rebasing
    rebase-strategy: "disabled"
