version: 2

updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "sunday"
    labels:
      - "dependency"
      - "need review"
    rebase-strategy: "disabled"
