detectors:
  IrresponsibleModule:
    enabled: false

  UncommunicativeModuleName:
    accept:
      - BoilerplateRailsApi
      - V1

  NestedIterators:
    max_allowed_nesting: 2
    ignore_iterators:
      - lambda

  DataClump:
    exclude:
      - DefaultEndpoint

  FeatureEnvy:
    exclude:
      - DefaultEndpoint#render_response

  TooManyStatements:
    exclude:
      - DefaultEndpoint#default_handler
      - Macro::Contract::BaseSchemaObject#self.Build
      - Macro::Contract#self.Schema
      - Macro::ModelDestroy#call
      - Macro#self.Model
      - Macro::ModelDelete#call
      - Macro::LinksBuilder#call
      - Macro::Assign#call
      - Macro::AddContractError#call
      - Macro::Inject#call
      - Macro::Decorate#call

  TooManyConstants:
    exclude:
      - JsonApi::Filtering::Predicates

  NilCheck:
    exclude:
      - Api::V1::Lib::Operation::Paginate#pagy

  UtilityFunction:
    exclude:
      - test_matcher
      - DefaultEndpoint#error_serializer_by_status
      - Service::JsonApi::ErrorDataStructureParser#compose_errors
      - Service::JsonApi::ErrorDataStructureParser#plain_errors?
      - Service::JsonApi::UriQueryErrorSerializer#compose_nested_errors
      - Macro::Contract::BaseSchemaObject#build_schema

  LongParameterList:
    max_params: 6

  ControlParameter:
    exclude:
      - Macro::Model#self.direction
      - Service::Pagy#call
      - Macro#self.Model
      - Macro::Decorate#call
      - Macro::Assign#call

  BooleanParameter:
    exclude:
      - Macro#self.Model
      - Macro::Assign#call

directories:
  'app/concepts':
    UtilityFunction:
      enabled: false

    DuplicateMethodCall:
      allow_calls:
        - 'ctx'

    FeatureEnvy:
      enabled: false

    DataClump:
      max_copies: 5

  'lib/macro':
    UncommunicativeMethodName:
      enabled: false

    FeatureEnvy:
      enabled: false

    DuplicateMethodCall:
      allow_calls:
        - 'ctx'

  'spec/support/helpers':
    UtilityFunction:
      enabled: false
    ControlParameter:
      enabled: false
    NilCheck:
      enabled: false

  'app/workers':
    UtilityFunction:
      enabled: false

exclude_paths:
  - db/
